name: Build site

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - "readingList.csv"
    - "generator.go"

concurrency: # Prevent two instances of this running at once
  group: deploy-to-ghpages
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run generator
        run: go run github.com/manuelmazzuola/readingList generateSite

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          publish_dir: .site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
